base_url = "https://yuraiz.github.io"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

title = "New Babylon"

[markdown]

[markdown.highlighting]
theme = "min-dark"

[search]
index_format = "fuse_javascript"

[extra]
# Put all your custom variables here
